// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgvFVS9Nn6gag7NmhHhG82TI0dKo4UkSg',
    appId: '1:192319133530:web:68c7199add9d46a1488563',
    messagingSenderId: '192319133530',
    projectId: 'with-eat',
    authDomain: 'with-eat.firebaseapp.com',
    storageBucket: 'with-eat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaUIANkn-AFhR3j1UT-BX74lBf1GAtEGQ',
    appId: '1:192319133530:android:f413bc66e3363484488563',
    messagingSenderId: '192319133530',
    projectId: 'with-eat',
    storageBucket: 'with-eat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHeSy6uhcpk_uZEpyNOhegADUCGDdlK0Q',
    appId: '1:192319133530:ios:88b10383735db00e488563',
    messagingSenderId: '192319133530',
    projectId: 'with-eat',
    storageBucket: 'with-eat.firebasestorage.app',
    iosBundleId: 'com.example.withEat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHeSy6uhcpk_uZEpyNOhegADUCGDdlK0Q',
    appId: '1:192319133530:ios:88b10383735db00e488563',
    messagingSenderId: '192319133530',
    projectId: 'with-eat',
    storageBucket: 'with-eat.firebasestorage.app',
    iosBundleId: 'com.example.withEat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgvFVS9Nn6gag7NmhHhG82TI0dKo4UkSg',
    appId: '1:192319133530:web:0ffa46a5745523df488563',
    messagingSenderId: '192319133530',
    projectId: 'with-eat',
    authDomain: 'with-eat.firebaseapp.com',
    storageBucket: 'with-eat.firebasestorage.app',
  );
}
